@startuml

entity Student {
    id : Integer PK // id
    ci : CharField(20) // Carnet de Identidad
    address : CharField(255) // Dirección
    grade : IntegerField // Grado
    last_name : CharField(255) // Apellidos
    first_name : CharField(255) // Nombres
    registration_number : CharField(255) // Número de Registro
    sex : CharField(10) // Sexo
    is_graduated : BooleanField // Graduado
    is_dropped_out : BooleanField // Baja
}

entity Dropout {
    id : Integer PK // id
    is_dropped_out : BooleanField // Baja
    date : DateField // Fecha
    municipality : CharField(255) // Municipio
    province : CharField(255) // Provincia
    school : CharField(255) // Escuela
}

entity Career {
    id : Integer PK // id
    amount : IntegerField // Monto
    name : CharField(255) // Nombre
}


entity Subject {
    id : Integer PK // id
    grade : IntegerField // Grado
    name : CharField(255) // Nombre
    tcp2_required : BooleanField // Requiere TCP2
}

entity SchoolYear {
    id : Integer PK
    startDate : Date
    endDate : Date
    name : Varchar(255)
}

entity StudentNote {
    id : Integer PK
    acs : FloatField // ACS
    final_grade : FloatField // Nota Final
    final_exam : FloatField // Examen Final
    tcp1 : FloatField // TCP1
    tcp2 : FloatField // TCP2
}



entity StudentCareer {
    id : Integer PK
    index : IntegerField // Índice
}

entity DegreeScale {
    ranking_score : FloatField // Nota Escalafón
    ranking_number : IntegerField // Número de Escalafón
}
entity GrantCareer{
    id : Integer PK
}

GrantCareer "1" -- "1" Student : Estudiante del otorgamiento
GrantCareer "1" -- "1" Career : Carrera otorgada


SchoolYear "1" -- "*" DegreeScale :  Curso del Escalafon
SchoolYear "1" -- "*" StudentNote : Curso de la nota

DegreeScale "1" -- "1" Student : Escalafon del estudiante

Student "1" -- "1" Dropout : student // Estudiante
Student "1" -- "*" StudentNote : student // Estudiante
Student "1" -- "*" StudentCareer : student // Estudiante



StudentNote "1" -- "1" Subject : subject // Asignatura
StudentCareer "*" -- "1" Career : career // Carrera

@enduml