@startuml

entity Student {
    id : Integer PK // id
    ci : CharField(20) // Carnet de Identidad
    address : CharField(255) // Dirección
    grade : IntegerField // Grado
    last_name : CharField(255) // Apellidos
    first_name : CharField(255) // Nombres
    registration_number : CharField(255) // Número de Registro
    sex : CharField(10) // Sexo
    is_graduated : BooleanField // Graduado
    is_dropped_out : BooleanField // Baja
}

entity Dropout {
    id : Integer PK // id
    date : DateField // Fecha
    municipality : CharField(255) // Municipio
    province : CharField(255) // Provincia
    school : CharField(255) // Escuela
}

entity Career {
    id : Integer PK // id
    amount : IntegerField // Monto
    name : CharField(255) // Nombre
}


entity Subject {
    id : Integer PK // id
    grade : IntegerField // Grado
    name : CharField(255) // Nombre
}

entity SchoolYear {
    id : Integer PK
    start_date : Date
    end_date : Date
    name : Varchar(255)
}

entity StudentNote {
    id : Integer PK
    average_acs : FloatField
    average_tcp : FloatField
    final_exam : FloatField
    final_grade : FloatField
    automatic_calculation: BooleanField
}



entity StudentCareer {
    id : Integer PK
    index : IntegerField // Índice
}

entity DegreeScale {
    ranking_score : FloatField // Nota Escalafón
    ranking_number : IntegerField // Número de Escalafón
}
entity GrantCareer{
    id : Integer PK
}

entity ApprovedSchoolCourse{
    id : Integer PK
    grade : IntegerField // Grado
    date : DateField // Fecha
}

entity SubjectSection{
    id : Integer PK
    title : CharField(255)
    description: CharField(255)
}
entity Folder{
    id : Integer PK
    title : CharField(255)
    description: CharField(255)
}
entity File{
    id : Integer PK
    title : CharField(255)
    description: CharField(255)
    type: CharField(255)
    url: CharField(255)
}
entity Professor {
    id : Integer PK
    ci : CharField(20)
    last_name : CharField(255)
    first_name : CharField(255)
}

entity SchoolTask{
    id : Integer PK
    date : DateField
    title : CharField(255)
    description: CharField(255)
    is_acs: BooleanField
    is_tcp: BooleanField
    is_final_exam: BooleanField

}
entity StudentResponse{
    id : Integer PK
    note : FloatField
    date : DateField
    description: CharField(255)
}

entity SchoolEvent {
    id : Integer PK
    date : DateTimeField
    title : CharField(255)
    description: CharField(255)
}

SchoolEvent "*" -- SchoolYear : Evento de Curso Escolar

SubjectSection "*" -- "1" SchoolYear : Seccion del curso
SubjectSection "*" -- "1" Subject : Seccion de asignatura
SchoolTask "*" -- "1" SubjectSection : Tarea de seccion

Folder "*" -- "1" SubjectSection : Carpeta de seccion
Folder "1" -- "*" File : Archivo de carpeta

SchoolTask "1" -- "*" File : Archivo de tarea
SchoolTask "1" -- "*" StudentResponse : Respuesta de Tarea

StudentResponse "1" -- "*" File : Archivo de respuesta
StudentResponse "*" -- "*" Student : Respuesta de Estudiante

Subject "*" -- "*" Professor : Profesor de seccion de asignatura

ApprovedSchoolCourse "1" -- "1" Student : Estudiante del curso aprobado
ApprovedSchoolCourse "*" -- "1" SchoolYear : Curso Escolar aprobado
ApprovedSchoolCourse "1" -- "1" GrantCareer : Otorgamiento en este curso aprobado

GrantCareer "1" -- "1" Student : Estudiante del otorgamiento
GrantCareer "*" -- "1" Career : Carrera otorgada


SchoolYear "1" -- "*" DegreeScale :  Curso del Escalafon
SchoolYear "1" -- "*" StudentNote : Curso de la nota

DegreeScale "1" -- "1" Student : Escalafon del estudiante

Student "1" -- "1" Dropout : student // Estudiante
Student "1" -- "*" StudentNote : student // Estudiante
Student "1" -- "*" StudentCareer : student // Estudiante



StudentNote "1" -- "1" Subject : subject // Asignatura
StudentCareer "*" -- "1" Career : career // Carrera

@enduml