# Generated by Django 4.2.7 on 2025-02-08 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_state", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Monto")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre"),
                ),
            ],
            options={
                "verbose_name": "Carrera",
                "verbose_name_plural": "Carreras",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_state", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "ci",
                    models.CharField(
                        max_length=20, verbose_name="Carnet de Identidad"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Dirección"),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[(7, 7), (8, 8), (9, 9)], verbose_name="Grado"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="Nombres"),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=255, verbose_name="Número de Registro"
                    ),
                ),
                ("sex", models.CharField(max_length=10, verbose_name="Sexo")),
                (
                    "is_graduated",
                    models.BooleanField(default=False, verbose_name="Graduado"),
                ),
                ("is_dropped_out", models.BooleanField(verbose_name="Baja")),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_state", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                ("grade", models.IntegerField(verbose_name="Grado")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre"),
                ),
                (
                    "tcp2_required",
                    models.BooleanField(verbose_name="Requiere TCP2"),
                ),
            ],
            options={
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
            },
        ),
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_state", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "acs",
                    models.FloatField(
                        blank=True, null=True, verbose_name="ACS"
                    ),
                ),
                (
                    "final_grade",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nota Final"
                    ),
                ),
                (
                    "final_exam",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Examen Final"
                    ),
                ),
                (
                    "tcp1",
                    models.FloatField(
                        blank=True, null=True, verbose_name="TCP1"
                    ),
                ),
                (
                    "tcp2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="TCP2"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.student",
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.subject",
                        verbose_name="Asignatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
            },
        ),
        migrations.CreateModel(
            name="StudentCareer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_state", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                ("index", models.IntegerField(verbose_name="Índice")),
                (
                    "career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.career",
                        verbose_name="Carrera",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudiante - Carrera",
                "verbose_name_plural": "Estudiantes - Carreras",
            },
        ),
        migrations.CreateModel(
            name="GraduationGrade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_state", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de Asignatura"
                    ),
                ),
                (
                    "assignment_grade",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nota de Asignación"
                    ),
                ),
                (
                    "tcp1",
                    models.FloatField(
                        blank=True, null=True, verbose_name="TCP1"
                    ),
                ),
                (
                    "tcp2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="TCP2"
                    ),
                ),
                (
                    "final_exam",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Examen Final"
                    ),
                ),
                (
                    "final_grade",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nota Final"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Graduado",
                "verbose_name_plural": "Notas de Graduados",
            },
        ),
        migrations.CreateModel(
            name="Graduation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_state", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "graduation_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Número de Matrícula",
                    ),
                ),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Graduación",
                    ),
                ),
                (
                    "career",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Carrera",
                    ),
                ),
                (
                    "ranking_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nota Escalafón"
                    ),
                ),
                (
                    "ranking_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de Escalafón",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Graduación",
                "verbose_name_plural": "Graduaciones",
            },
        ),
        migrations.CreateModel(
            name="Dropout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_state", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                ("is_dropped_out", models.BooleanField(verbose_name="Baja")),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "municipality",
                    models.CharField(max_length=255, verbose_name="Municipio"),
                ),
                (
                    "province",
                    models.CharField(max_length=255, verbose_name="Provincia"),
                ),
                (
                    "school",
                    models.CharField(max_length=255, verbose_name="Escuela"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baja",
                "verbose_name_plural": "Bajas",
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model_state", models.BooleanField(default=True)),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                (
                    "graduation_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Año de Graduación"
                    ),
                ),
                (
                    "career",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Carrera",
                    ),
                ),
                (
                    "ranking_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nota Escalafón"
                    ),
                ),
                (
                    "ranking_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de Escalafón",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otorgamiento",
                "verbose_name_plural": "Otorgamientos",
            },
        ),
    ]
