# Generated by Django 4.2.7 on 2025-02-15 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_rename_enddate_schoolyear_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DegreeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ranking_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nota Escalafón"
                    ),
                ),
                (
                    "ranking_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de Escalafón",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.schoolyear",
                        verbose_name="Año escolar",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalafón Estudiantil",
                "verbose_name_plural": "Escalafones Estudiantiles",
            },
        ),
    ]
