# Generated by Django 4.2.7 on 2025-02-15 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_degreescale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentnote",
            old_name="acs",
            new_name="asc",
        ),
    ]
