# Generated by Django 4.2.7 on 2025-02-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_rename_acs_studentnote_asc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="ci",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Carnet de Identidad"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="sex",
            field=models.CharField(
                choices=[("F", "Femenino"), ("M", "Masculino")],
                max_length=10,
                verbose_name="Sexo",
            ),
        ),
    ]
