# Generated by Django 4.2.7 on 2025-02-16 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_student_ci_alter_student_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrantCareer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.career",
                        verbose_name="Carrera",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.schoolyear",
                        verbose_name="Año escolar",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrera Otorgada",
                "verbose_name_plural": "Carreras Otorgadas",
            },
        ),
        migrations.RemoveField(
            model_name="graduation",
            name="student",
        ),
        migrations.RemoveField(
            model_name="graduationgrade",
            name="student",
        ),
        migrations.AlterField(
            model_name="subject",
            name="grade",
            field=models.IntegerField(
                choices=[(7, 7), (8, 8), (9, 9)], verbose_name="Grado"
            ),
        ),
        migrations.DeleteModel(
            name="Award",
        ),
        migrations.DeleteModel(
            name="Graduation",
        ),
        migrations.DeleteModel(
            name="GraduationGrade",
        ),
    ]
