# Generated by Django 4.2.7 on 2025-02-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_grantcareer_remove_graduation_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_dropped_out",
            field=models.BooleanField(default=False, verbose_name="Baja"),
        ),
    ]
