# Generated by Django 4.2.7 on 2025-02-20 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_alter_career_name_alter_student_is_dropped_out"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dropout",
            name="is_dropped_out",
        ),
    ]
