# Generated by Django 4.2.7 on 2025-02-20 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_remove_dropout_is_dropped_out"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grantcareer",
            name="school_year",
        ),
        migrations.CreateModel(
            name="ApprovedSchoolCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "grade",
                    models.IntegerField(
                        choices=[(7, 7), (8, 8), (9, 9)], verbose_name="Grado"
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.schoolyear",
                        verbose_name="Año escolar",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso Escolar Aprobado",
                "verbose_name_plural": "Cursos Escolares Aprobados",
            },
        ),
        migrations.AddField(
            model_name="grantcareer",
            name="approved_school_course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.approvedschoolcourse",
                verbose_name="Curso Escolar Aprobado",
            ),
            preserve_default=False,
        ),
    ]
