# Generated by Django 4.2.7 on 2025-02-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project",
            "0010_remove_grantcareer_school_year_approvedschoolcourse_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ci",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Carnet de Identidad",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Dirección"),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[(7, 7), (8, 8), (9, 9)], verbose_name="Grado"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="Nombres"),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("F", "Femenino"), ("M", "Masculino")],
                        max_length=10,
                        verbose_name="Sexo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesor",
                "verbose_name_plural": "Profesores",
            },
        ),
        migrations.CreateModel(
            name="ProfessorEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(verbose_name="Nota")),
                ("date", models.DateField(verbose_name="Fecha")),
                ("description", models.TextField(verbose_name="Descripcion")),
            ],
            options={
                "verbose_name": "Evaluación del Profesor",
                "verbose_name_plural": "Evaluaciones de los Profesores",
            },
        ),
        migrations.CreateModel(
            name="SchoolEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Fecha")),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titulo"),
                ),
                ("description", models.TextField(verbose_name="Descripcion")),
            ],
            options={
                "verbose_name": "Evento Escolar",
                "verbose_name_plural": "Eventos Escolares",
            },
        ),
        migrations.CreateModel(
            name="StudentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                ("description", models.TextField(verbose_name="Descripcion")),
            ],
            options={
                "verbose_name": "Respuesta del Estudiante",
                "verbose_name_plural": "Respuestas de los Estudiantes",
            },
        ),
        migrations.CreateModel(
            name="SubjectSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titulo"),
                ),
                ("description", models.TextField(verbose_name="Descripcion")),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.schoolyear",
                        verbose_name="Año escolar",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.subject",
                        verbose_name="Asignatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección de Asignatura",
                "verbose_name_plural": "Secciones de Asignaturas",
            },
        ),
        migrations.CreateModel(
            name="SchoolTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titulo"),
                ),
                ("description", models.TextField(verbose_name="Descripcion")),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "is_acs",
                    models.BooleanField(default=False, verbose_name="Acs"),
                ),
                (
                    "is_tcp",
                    models.BooleanField(default=False, verbose_name="Tcp"),
                ),
                (
                    "is_final_exam",
                    models.BooleanField(
                        default=False, verbose_name="Examen Final"
                    ),
                ),
                (
                    "subject_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.subjectsection",
                        verbose_name="Sección de Asignatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea Escolar",
                "verbose_name_plural": "Tareas Escolares",
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titulo"),
                ),
                ("description", models.TextField(verbose_name="Descripcion")),
                (
                    "subject_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.subjectsection",
                        verbose_name="Sección de Asignatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carpeta",
                "verbose_name_plural": "Carpetas",
            },
        ),
        migrations.CreateModel(
            name="FileStudentResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titulo"),
                ),
                ("description", models.TextField(verbose_name="Descripcion")),
                ("type", models.CharField(max_length=255, verbose_name="Tipo")),
                (
                    "file",
                    models.FileField(upload_to="", verbose_name="Archivo"),
                ),
                (
                    "student_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.studentresponse",
                        verbose_name="Respuesta del Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo De Respuesta del Estudiante",
                "verbose_name_plural": "Archivos De Respuestas de los Estudiantes",
            },
        ),
        migrations.CreateModel(
            name="FileSchoolTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titulo"),
                ),
                ("description", models.TextField(verbose_name="Descripcion")),
                ("type", models.CharField(max_length=255, verbose_name="Tipo")),
                (
                    "file",
                    models.FileField(upload_to="", verbose_name="Archivo"),
                ),
                (
                    "school_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.schooltask",
                        verbose_name="Tarea Escolar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo De Tarea Escolar",
                "verbose_name_plural": "Archivos De Tareas Escolares",
            },
        ),
        migrations.CreateModel(
            name="FileFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titulo"),
                ),
                ("description", models.TextField(verbose_name="Descripcion")),
                ("type", models.CharField(max_length=255, verbose_name="Tipo")),
                (
                    "file",
                    models.FileField(upload_to="", verbose_name="Archivo"),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.folder",
                        verbose_name="Carpeta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo De Carpeta",
                "verbose_name_plural": "Archivos De Carpetas",
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="professor",
            field=models.ManyToManyField(
                to="project.professor", verbose_name="Profesores"
            ),
        ),
    ]
