# Generated by Django 4.2.7 on 2025-02-23 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_professor_professorevaluation_schoolevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professorevaluation",
            name="professor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.professor",
                verbose_name="Profesor",
            ),
            preserve_default=False,
        ),
    ]
