# Generated by Django 4.2.7 on 2025-02-25 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0014_remove_professor_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schooltask",
            name="is_acs",
        ),
        migrations.RemoveField(
            model_name="schooltask",
            name="is_final_exam",
        ),
        migrations.RemoveField(
            model_name="schooltask",
            name="is_tcp",
        ),
        migrations.DeleteModel(
            name="ProfessorEvaluation",
        ),
    ]
