# Generated by Django 4.2.7 on 2025-02-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0015_remove_schooltask_is_acs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectsection",
            name="index",
            field=models.IntegerField(default=1, verbose_name="Indice"),
        ),
    ]
