# Generated by Django 4.2.7 on 2025-02-27 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0016_subjectsection_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentresponse",
            name="school_task",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.schooltask",
                verbose_name="Tarea Escolar",
            ),
            preserve_default=False,
        ),
    ]
