# Generated by Django 4.2.7 on 2025-02-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0017_studentresponse_school_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filefolder",
            name="file",
            field=models.CharField(max_length=500, verbose_name="Archivo"),
        ),
        migrations.AlterField(
            model_name="fileschooltask",
            name="file",
            field=models.CharField(max_length=500, verbose_name="Archivo"),
        ),
        migrations.AlterField(
            model_name="filestudentresponse",
            name="file",
            field=models.CharField(max_length=500, verbose_name="Archivo"),
        ),
    ]
