# Generated by Django 4.2.7 on 2025-03-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0019_studentresponse_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filefolder",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripcion"
            ),
        ),
        migrations.AlterField(
            model_name="fileschooltask",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripcion"
            ),
        ),
        migrations.AlterField(
            model_name="filestudentresponse",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripcion"
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripcion"
            ),
        ),
        migrations.AlterField(
            model_name="schoolevent",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripcion"
            ),
        ),
        migrations.AlterField(
            model_name="schooltask",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripcion"
            ),
        ),
        migrations.AlterField(
            model_name="studentresponse",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="studentresponse",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripcion"
            ),
        ),
        migrations.AlterField(
            model_name="subjectsection",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripcion"
            ),
        ),
    ]
