# Generated by Django 4.2.7 on 2025-03-05 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0020_alter_filefolder_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre"),
                ),
                (
                    "professors",
                    models.ManyToManyField(
                        to="project.professor", verbose_name="Profesores"
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.schoolyear",
                        verbose_name="Año escolar",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        to="project.student", verbose_name="Estudiantes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Estudiante",
                "verbose_name_plural": "Grupos de Estudiantes",
            },
        ),
    ]
