# Generated by Django 4.2.7 on 2025-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0021_studentgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="grade",
            field=models.IntegerField(
                choices=[(7, 7), (8, 8), (9, 9)],
                default=7,
                verbose_name="Grado",
            ),
            preserve_default=False,
        ),
    ]
