# Generated by Django 4.2.7 on 2025-03-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0022_studentgroup_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropout",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.student",
                unique=True,
                verbose_name="Estudiante",
            ),
        ),
    ]
