# Generated by Django 4.2.7 on 2025-03-07 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0023_alter_dropout_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentgroup",
            name="students",
        ),
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.studentgroup",
                verbose_name="Grupo",
            ),
        ),
    ]
