# Generated by Django 4.2.7 on 2025-03-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0024_remove_studentgroup_students_student_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentgroup",
            name="school_year",
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="name",
            field=models.CharField(
                help_text="ejemplo: 2024-2025",
                max_length=255,
                unique=True,
                verbose_name="Nombre",
            ),
        ),
    ]
