# Generated by Django 4.2.7 on 2025-03-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0025_remove_studentgroup_school_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropout",
            name="is_dropout",
            field=models.BooleanField(default=False, verbose_name="Es Baja"),
        ),
    ]
